MVC_EF/Controllers/tblContactsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_EF.Models;

namespace MVC_EF.Controllers
{
    public class tblContactsController : Controller
    {
        private ContactModel db = new ContactModel();
        
        // GET: tblContacts
        public ActionResult Index(string sortBy)
        {
            ViewBag.SortNameParameter = string.IsNullOrEmpty(sortBy) ? "Name desc" : "";
            ViewBag.SortGenderParameter = string.IsNullOrEmpty(sortBy) ? "Gender desc" : "Gender";
            ViewBag.SortLnameParameter = string.IsNullOrEmpty(sortBy) ? "Lname desc" : "Lname";
            ViewBag.SortTnameParameter = string.IsNullOrEmpty(sortBy) ? "Tname desc" : "Tname";
            ViewBag.SortDobParameter = string.IsNullOrEmpty(sortBy) ? "Dob desc" : "Dob";
            ViewBag.SortAgeParameter = string.IsNullOrEmpty(sortBy) ? "Age desc" : "Age";
                       
            var contacts = db.tblContacts.AsQueryable();

            switch (sortBy)
            {
                case "Name desc":
                    contacts = contacts.OrderByDescending(x => x.Name);
                    break;
                case "Gender desc":
                    contacts = contacts.OrderByDescending(x => x.Gender);
                    break;
                case "Gender":
                    contacts = contacts.OrderBy(x => x.Gender);
                    break;
                case "Lname desc":
                    contacts = contacts.OrderByDescending(x => x.Lname);
                    break;
                case "Lname":
                    contacts = contacts.OrderBy(x => x.Lname);
                    break;
                case "Tname desc":
                    contacts = contacts.OrderByDescending(x => x.Tname);
                    break;
                case "Tname":
                    contacts = contacts.OrderBy(x => x.Tname);
                    break;
                case "Dob desc":
                    contacts = contacts.OrderByDescending(x => x.DateOfBirth);
                    break;
                case "Dob":
                    contacts = contacts.OrderBy(x => x.DateOfBirth);
                    break;
                case "Age desc":
                    contacts = contacts.OrderByDescending(x => x.Age);
                    break;
                case "Age":
                    contacts = contacts.OrderBy(x => x.Age);
                    break;
                default:
                    contacts = contacts.OrderBy(x => x.Name);
                    break;
            }

            return View(contacts);            
        }

        // GET: tblContacts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblContacts tblContacts = db.tblContacts.Find(id);
            
            if (tblContacts == null)
            {
                return HttpNotFound();
            }
            return View(tblContacts);
        }

        // GET: tblContacts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: tblContacts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Lname,Tname,DateOfBirth,Gender")] tblContacts tblContacts)
        {

            //calculates the age using the dateOfBirth from text control 
            tblContacts.Age = Convert.ToInt32(Age(tblContacts.DateOfBirth));

            if (ModelState.IsValid)
            {
                db.tblContacts.Add(tblContacts);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblContacts);
        }

        // GET: tblContacts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblContacts tblContacts = db.tblContacts.Find(id);
            if (tblContacts == null)
            {
                return HttpNotFound();
            }
            return View(tblContacts);
        }

        // POST: tblContacts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Lname,Tname,DateOfBirth,Gender")] tblContacts tblContacts)
        {
            tblContacts.Age = Convert.ToInt32(Age(tblContacts.DateOfBirth));

            if (ModelState.IsValid)
            {
                db.Entry(tblContacts).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblContacts);
        }

        // GET: tblContacts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblContacts tblContacts = db.tblContacts.Find(id);
            if (tblContacts == null)
            {
                return HttpNotFound();
            }
            return View(tblContacts);
        }

        // POST: tblContacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblContacts tblContacts = db.tblContacts.Find(id);
            db.tblContacts.Remove(tblContacts);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteMultiple(IEnumerable<int> contactIdsToDelete)
        {
            List<tblContacts> lst = db.tblContacts.Where(x => contactIdsToDelete.Contains(x.Id)).ToList();

            foreach (tblContacts contact in lst)
            {
                db.tblContacts.Remove(contact);
            }
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public static string Age(DateTime birthday)
        {
            DateTime now = DateTime.Today;
            int age = now.Year - birthday.Year;
            if (now < birthday.AddYears(age)) age--;

            return age.ToString();
        }
    }
}

MVC_EF/Views/tblContacts/Create.cshtml
@model MVC_EF.Models.tblContacts

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Gender", new List<SelectListItem>
           {
               new SelectListItem { Text="Мужской", Value="Мужской"},
               new SelectListItem { Text="Женский", Value="Женский"},
               new SelectListItem { Text="Не указан", Value="Не указан"}
           }, "Выберите пол")
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_EF/Views/tblContacts/Delete.cshtml
@model MVC_EF.Models.tblContacts

@{
    ViewBag.Title = "Delete";
}

<h2>Удалить</h2>

<h3>Вы точно хотите удалить данный контакт?</h3>
<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Назад к списку", "Index")
        </div>
    }
</div>

MVC_EF/Views/tblContacts/Details.cshtml
@model MVC_EF.Models.tblContacts

@{
    ViewBag.Title = "Details";
}

<h2>Информация</h2>

<div>
 
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Назад к списку", "Index")
</p>

MVC_EF/Views/tblContacts/Edit.cshtml
@model MVC_EF.Models.tblContacts


@{
    ViewBag.Title = "Edit";
}

<h2>Редактировать</h2>



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

         
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })               
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Gender", new List<SelectListItem>
                                    {
                                        new SelectListItem { Text="Мужской", Value="Мужской"},
                                        new SelectListItem { Text="Женский", Value="Женский"},
                                        new SelectListItem { Text="Не выбрано", Value="Не выбрано"}
                                    }, 
                                    "Выберите пол")
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад к списку", "Index")
</div>

@section Scripts {)
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_EF/Views/tblContacts/Index.cshtml
@model IEnumerable<MVC_EF.Models.tblContacts>

@{  
    ViewBag.Title = "Index";
}

<link rel="stylesheet" type="text/css" href="~/Content/Site.css">
<p>
    @Html.ActionLink("Создать новый контакт", "Create")
</p>

@using (Html.BeginForm("DeleteMultiple", "tblContacts", FormMethod.Post))
{
<table class="table">
    <tr>
        <th>

        </th>
        <th >
            @Html.ActionLink("Имя", "Index", new { sortBy = ViewBag.SortNameParameter })
        </th>
        <th>
            @Html.ActionLink("Фамилия", "Index", new { sortBy = ViewBag.SortLnameParameter })
        </th>
        <th>
            @Html.ActionLink("Отчество", "Index", new { sortBy = ViewBag.SortTnameParameter })
        </th>
        <th>
            @Html.ActionLink("Дата рождения", "Index", new { sortBy = ViewBag.SortDobParameter })
        </th>
        <th>
            @Html.ActionLink("Пол", "Index", new { sortBy = ViewBag.SortGenderParameter })
        </th>
        <th>
            @Html.ActionLink("Возраст", "Index", new { sortBy = ViewBag.SortAgeParameter })
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            <input type="checkbox" name="contactIdsToDelete" id="contactIdsToDelete" value="@item.Id" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOfBirth)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Age)
        </td>
        <td>
            @Html.ActionLink("Редактировать", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Инфо", "Details", new { id = item.Id }) |
            @Html.ActionLink("Удалить", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>

<input type="submit"  value="Удалить выбранные" />
}